# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SDA.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_L3TServiceDeskAssistant(object):
    def setupUi(self, L3TServiceDeskAssistant):
        L3TServiceDeskAssistant.setObjectName("L3TServiceDeskAssistant")
        L3TServiceDeskAssistant.resize(788, 660)
        self.centralwidget = QtWidgets.QWidget(L3TServiceDeskAssistant)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.cmbAttempt = QtWidgets.QComboBox(self.tab)
        self.cmbAttempt.setGeometry(QtCore.QRect(10, 150, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.cmbAttempt.setFont(font)
        self.cmbAttempt.setObjectName("cmbAttempt")
        self.cmbAttempt.addItem("")
        self.cmbAttempt.addItem("")
        self.cmbAttempt.addItem("")
        self.lblTicketNumber = QtWidgets.QLabel(self.tab)
        self.lblTicketNumber.setGeometry(QtCore.QRect(0, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTicketNumber.setFont(font)
        self.lblTicketNumber.setObjectName("lblTicketNumber")
        self.lblEUName = QtWidgets.QLabel(self.tab)
        self.lblEUName.setGeometry(QtCore.QRect(30, 60, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEUName.setFont(font)
        self.lblEUName.setObjectName("lblEUName")
        self.lblPhoneNumber = QtWidgets.QLabel(self.tab)
        self.lblPhoneNumber.setGeometry(QtCore.QRect(10, 100, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPhoneNumber.setFont(font)
        self.lblPhoneNumber.setObjectName("lblPhoneNumber")
        self.btnGenerate = QtWidgets.QPushButton(self.tab)
        self.btnGenerate.setGeometry(QtCore.QRect(150, 150, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnGenerate.setFont(font)
        self.btnGenerate.setObjectName("btnGenerate")
        self.txtCBOutput = QtWidgets.QPlainTextEdit(self.tab)
        self.txtCBOutput.setGeometry(QtCore.QRect(10, 210, 371, 221))
        self.txtCBOutput.setObjectName("txtCBOutput")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 311, 16))
        self.label_4.setObjectName("label_4")
        self.btnClear = QtWidgets.QPushButton(self.tab)
        self.btnClear.setGeometry(QtCore.QRect(10, 440, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.txtTicketNumber = QtWidgets.QLineEdit(self.tab)
        self.txtTicketNumber.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.txtTicketNumber.setObjectName("txtTicketNumber")
        self.txtEUName = QtWidgets.QLineEdit(self.tab)
        self.txtEUName.setGeometry(QtCore.QRect(130, 60, 113, 20))
        self.txtEUName.setObjectName("txtEUName")
        self.txtPhoneNumber = QtWidgets.QLineEdit(self.tab)
        self.txtPhoneNumber.setGeometry(QtCore.QRect(130, 100, 113, 20))
        self.txtPhoneNumber.setObjectName("txtPhoneNumber")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lblEuName = QtWidgets.QLabel(self.tab_2)
        self.lblEuName.setGeometry(QtCore.QRect(10, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEuName.setFont(font)
        self.lblEuName.setObjectName("lblEuName")
        self.lblPERNR = QtWidgets.QLabel(self.tab_2)
        self.lblPERNR.setGeometry(QtCore.QRect(10, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPERNR.setFont(font)
        self.lblPERNR.setObjectName("lblPERNR")
        self.txtEuName = QtWidgets.QLineEdit(self.tab_2)
        self.txtEuName.setGeometry(QtCore.QRect(150, 30, 113, 20))
        self.txtEuName.setObjectName("txtEuName")
        self.txtFolderPath = QtWidgets.QLineEdit(self.tab_2)
        self.txtFolderPath.setGeometry(QtCore.QRect(150, 90, 113, 20))
        self.txtFolderPath.setObjectName("txtFolderPath")
        self.txtPocTicketNumber = QtWidgets.QLineEdit(self.tab_2)
        self.txtPocTicketNumber.setGeometry(QtCore.QRect(150, 120, 113, 20))
        self.txtPocTicketNumber.setObjectName("txtPocTicketNumber")
        self.lblticketNumber = QtWidgets.QLabel(self.tab_2)
        self.lblticketNumber.setGeometry(QtCore.QRect(10, 120, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblticketNumber.setFont(font)
        self.lblticketNumber.setObjectName("lblticketNumber")
        self.btnRequest = QtWidgets.QPushButton(self.tab_2)
        self.btnRequest.setGeometry(QtCore.QRect(10, 180, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnRequest.setFont(font)
        self.btnRequest.setObjectName("btnRequest")
        self.btnAccessGranted = QtWidgets.QPushButton(self.tab_2)
        self.btnAccessGranted.setGeometry(QtCore.QRect(130, 180, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnAccessGranted.setFont(font)
        self.btnAccessGranted.setObjectName("btnAccessGranted")
        self.txtOutput = QtWidgets.QPlainTextEdit(self.tab_2)
        self.txtOutput.setGeometry(QtCore.QRect(10, 210, 421, 211))
        self.txtOutput.setObjectName("txtOutput")
        self.btnClearFields = QtWidgets.QPushButton(self.tab_2)
        self.btnClearFields.setGeometry(QtCore.QRect(10, 440, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnClearFields.setFont(font)
        self.btnClearFields.setObjectName("btnClearFields")
        self.txtPERNR = QtWidgets.QLineEdit(self.tab_2)
        self.txtPERNR.setGeometry(QtCore.QRect(150, 60, 113, 20))
        self.txtPERNR.setObjectName("txtPERNR")
        self.lblFolderPath_2 = QtWidgets.QLabel(self.tab_2)
        self.lblFolderPath_2.setGeometry(QtCore.QRect(10, 90, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblFolderPath_2.setFont(font)
        self.lblFolderPath_2.setObjectName("lblFolderPath_2")
        self.cmbAccess = QtWidgets.QComboBox(self.tab_2)
        self.cmbAccess.setGeometry(QtCore.QRect(10, 150, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        self.cmbAccess.setFont(font)
        self.cmbAccess.setObjectName("cmbAccess")
        self.cmbAccess.addItem("")
        self.cmbAccess.addItem("")
        self.cmbAccess.addItem("")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(270, 120, 171, 16))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 511, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(5, 4, item)
        self.tabWidget.addTab(self.tab_3, "")
        L3TServiceDeskAssistant.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(L3TServiceDeskAssistant)
        self.statusbar.setObjectName("statusbar")
        L3TServiceDeskAssistant.setStatusBar(self.statusbar)

        self.retranslateUi(L3TServiceDeskAssistant)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(L3TServiceDeskAssistant)

    def retranslateUi(self, L3TServiceDeskAssistant):
        _translate = QtCore.QCoreApplication.translate
        L3TServiceDeskAssistant.setWindowTitle(_translate("L3TServiceDeskAssistant", "L3T Service Desk Assistant"))
        self.cmbAttempt.setItemText(0, _translate("L3TServiceDeskAssistant", "1st Attempt"))
        self.cmbAttempt.setItemText(1, _translate("L3TServiceDeskAssistant", "2nd Attempt"))
        self.cmbAttempt.setItemText(2, _translate("L3TServiceDeskAssistant", "3rd Attempt"))
        self.lblTicketNumber.setText(_translate("L3TServiceDeskAssistant", "Ticket Number:"))
        self.lblEUName.setText(_translate("L3TServiceDeskAssistant", "EU\'s Name:"))
        self.lblPhoneNumber.setText(_translate("L3TServiceDeskAssistant", "Phone Number:"))
        self.btnGenerate.setText(_translate("L3TServiceDeskAssistant", "Generate"))
        self.label_4.setText(_translate("L3TServiceDeskAssistant", "Copy/Paste this into ticket comments or email. "))
        self.btnClear.setText(_translate("L3TServiceDeskAssistant", "Clear Fields"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("L3TServiceDeskAssistant", "Callbacks"))
        self.lblEuName.setText(_translate("L3TServiceDeskAssistant", "EU Name:"))
        self.lblPERNR.setText(_translate("L3TServiceDeskAssistant", "PERNR:"))
        self.lblticketNumber.setText(_translate("L3TServiceDeskAssistant", "Ticket Number:"))
        self.btnRequest.setText(_translate("L3TServiceDeskAssistant", "Request"))
        self.btnAccessGranted.setText(_translate("L3TServiceDeskAssistant", "Access Granted"))
        self.btnClearFields.setText(_translate("L3TServiceDeskAssistant", "Clear Fields"))
        self.lblFolderPath_2.setText(_translate("L3TServiceDeskAssistant", "Folder Path:"))
        self.cmbAccess.setItemText(0, _translate("L3TServiceDeskAssistant", "Read/Write Access"))
        self.cmbAccess.setItemText(1, _translate("L3TServiceDeskAssistant", "Read Only Access"))
        self.cmbAccess.setItemText(2, _translate("L3TServiceDeskAssistant", "Full Control"))
        self.label.setText(_translate("L3TServiceDeskAssistant", "*Only required for Acess Granted"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("L3TServiceDeskAssistant", "PoC Shared Folder/Drive Access"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("L3TServiceDeskAssistant", " A - Aplha"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("L3TServiceDeskAssistant", "B - Bravo"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("L3TServiceDeskAssistant", "C - Charlie"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("L3TServiceDeskAssistant", "D - Delta"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("L3TServiceDeskAssistant", "E - Echo"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("L3TServiceDeskAssistant", "F - Foxtrot"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("L3TServiceDeskAssistant", "G - Golf"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("L3TServiceDeskAssistant", "H - Hotel"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("L3TServiceDeskAssistant", "I - India"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("L3TServiceDeskAssistant", "J - Juliet"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("L3TServiceDeskAssistant", "K - Kilo"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("L3TServiceDeskAssistant", "L - Lima"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("L3TServiceDeskAssistant", "M - Mike"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("L3TServiceDeskAssistant", "N - November"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("L3TServiceDeskAssistant", "O - Oscar"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("L3TServiceDeskAssistant", "P - Papa"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("L3TServiceDeskAssistant", "Q - Quebec"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("L3TServiceDeskAssistant", "R - Romeo"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("L3TServiceDeskAssistant", "S - Sierra"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("L3TServiceDeskAssistant", "T - Tango"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("L3TServiceDeskAssistant", "U - Uniform"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("L3TServiceDeskAssistant", "V - Victor"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("L3TServiceDeskAssistant", "W - Whiskey"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("L3TServiceDeskAssistant", "X - X-ray"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("L3TServiceDeskAssistant", "Y - Yankee"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("L3TServiceDeskAssistant", "Z - Zulu"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("L3TServiceDeskAssistant", "NATO Phonetic Alphabet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    L3TServiceDeskAssistant = QtWidgets.QMainWindow()
    ui = Ui_L3TServiceDeskAssistant()
    ui.setupUi(L3TServiceDeskAssistant)
    L3TServiceDeskAssistant.show()
    sys.exit(app.exec_())

